name: Build Binaries

on: 
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  build_for_mac:
    name: MacOS
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/scant3r scant3r-macos64
      - name: strip
        run: strip scant3r-macos64
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -f \
            -sSL \
            -XPOST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Length: $(stat -f%z scant3r-macos64)" \
            -H "Content-Type: application/octet-stream" \
            --upload-file "scant3r-macos64" \
            "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets?name=scant3r-macos64"

  build_for_linux:
    name: Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/scant3r scant3r-linux-amd64
      - name: strip
        run: strip scant3r-linux-amd64
      - name: Upload to release
        uses: JasonEtco/upload-to-release@d648f1babf776de9cad881320bd9e9818fc3b262
        with:
          args: scant3r-linux-amd64 application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
